.goreleaser.yml
name: yaks

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - main: .
    binary: yaks
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/todda86/yaks/cmd.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - repository:
      owner: todda86
      name: homebrew-tap
    commit_author:
      name: yaks
      email: yaks@users.noreply.github.com
    homepage: https://github.com/todda86/yaks
    description: A Kubernetes context & namespace switcher
    license: MIT
